title: Akanksha Gavade # your name (or website title) here
logo: "/images/the_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/akanksha-gavade/">LinkedIn</a> 
  <br>
  # <a href="https://bowen.finance/cv/" class="btn btn--info">Resume</a>  
  <a href="/images/resume/pdf?raw=true">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/akankshagavade">GitHub</a>  
  # <br>
  # <a href="https://www.GitHub.com/donbowen/">Twitter</a>  
  # <br>
  # <a href="https://www.GitHub.com/donbowen/">Youtube</a> 
  
theme: jekyll-theme-minimal
