title: Akanksha Gavade # your name (or website title) here
logo: "/images/the_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Relevant links: 
  <br><br>
  <a href="https://www.linkedin.com/in/akanksha-gavade/">LinkedIn</a> 
  <br>
  <a href="/images/resume.pdf?raw=true">Resume</a>  
  _**[Resume](images/resume.pdf)**_

  <br>
  <a href="https://github.com/akankshagavade">GitHub</a>  

  
theme: jekyll-theme-minimal
